# Generated by Django 5.0.6 on 2024-08-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('A', 'Новая'), ('B', 'Отличное'), ('C', 'Хорошее'), ('D', 'Среднее'), ('F', 'Плохое')], max_length=1, verbose_name='Состояние книги'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cover_type',
            field=models.CharField(choices=[('A', 'Твердый'), ('B', 'Мягкий'), ('X', 'Другой')], max_length=1, verbose_name='Переплет'),
        ),
    ]
