# Generated by Django 4.2.5 on 2024-04-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_translations',
            field=models.JSONField(default=2, verbose_name='Translated Names'),
            preserve_default=False,
        ),
    ]
