# Generated by Django 4.2.5 on 2024-05-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_category_image_category_name_en_category_name_kk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='created_by',
            new_name='seller',
        ),
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(default=134, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('Н', 'Новая'), ('О', 'Отличное'), ('Х', 'Хорошее'), ('С', 'Среднее'), ('П', 'Плохое')], default=41, max_length=1, verbose_name='Состояние книги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='cover_type',
            field=models.CharField(choices=[('Т', 'Твердый переплет'), ('М', 'Мягкая обложка'), ('К', 'Переплет из картона'), ('И', 'Интегральный переплет'), ('С', 'Суперобложка'), ('Д', 'Другой')], default=1, max_length=1, verbose_name='Переплет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/<django.db.models.fields.related.ForeignKey>/images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='language',
            field=models.CharField(choices=[('RU', 'Русский'), ('KZ', 'Казахский'), ('EN', 'Английский'), ('OT', 'Другой')], default=1, max_length=2, verbose_name='Язык'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='publisher',
            field=models.CharField(default=1, max_length=100, verbose_name='Издательство'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/<django.db.models.fields.related.ForeignKey>/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
    ]
