# Generated by Django 4.2.5 on 2024-04-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_category_name_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_translations',
        ),
        migrations.AddField(
            model_name='category',
            name='translations',
            field=models.JSONField(default=1, verbose_name='Translations'),
            preserve_default=False,
        ),
    ]
