# Generated by Django 4.2.5 on 2024-04-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_remove_category_name_translations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='translations',
        ),
        migrations.AddField(
            model_name='category',
            name='name_translations',
            field=models.JSONField(default=1, verbose_name='Translated Names'),
            preserve_default=False,
        ),
    ]
