# Generated by Django 4.2.5 on 2024-05-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_category_translations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
    ]
