# Generated by Django 4.2.5 on 2024-05-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='Цена'),
        ),
    ]
