# Generated by Django 4.2.5 on 2024-05-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image1',
            field=models.ImageField(default='default.jpg', upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(default='default.jpg', upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(default='default.jpg', upload_to='item_images/'),
        ),
    ]
