# Generated by Django 4.2 on 2023-09-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reSite', '0003_booklisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklisting',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True),
        ),
    ]
