# Generated by Django 4.2 on 2023-09-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reSite', '0010_profile_viewer_profile_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='viewer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='visibility',
        ),
    ]
