# Generated by Django 4.2 on 2023-09-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reSite', '0004_booklisting_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklisting',
            name='unique_number',
            field=models.PositiveIntegerField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
