# Generated by Django 4.2 on 2023-09-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reSite', '0006_category_booklisting_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklisting',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
