# Generated by Django 4.2 on 2023-09-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reSite', '0007_remove_booklisting_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklisting',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
