# Generated by Django 4.2.5 on 2023-10-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reSite', '0013_advertisement_advertisementimage_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
